django-learning/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

django-learning/mysite/polls/urls.py
# tell django where tf to grab
from django.urls import path

# pull in the data from views
from . import views

app_name = 'polls'
urlpatterns = [
        # i think int:pk helps with generic Views - see views.py
        # ex: polls/
        path('', views.IndexView.as_view(), name='index'),
        # ex: polls/5
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        # ex: polls/5/results
        path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
        # ex: polls/5/vote
        path('<int:question_id>/vote/', views.vote, name='vote'),
    ]

""" /*old code when functions were set as index, detail, etc => just calling fn's
    also notice old code uses <int:question_id> instead of pk, just different calls baby */
urlpatterns = [
        # ex: polls/
        path('', views.index, name='index'),
        # ex: polls/5
        path('<int:question_id>/', views.detail, name='detail'),
        # ex: polls/5/results
        path('<int:question_id>/results/', views.results, name='results'),
        # ex: polls/5/vote
        path('<int:question_id>/vote/', views.vote, name='vote'),
    ]
"""

django-learning/mysite/polls/models.py
from django.db import models

# Create your models here.

# working with manage.py this can build a table and columns in a database - this is configured with sqlite but others available
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    # use to get more readable returns from calling class
    def __str__(self):
        return self.question_text
    # this is a custom method
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

django-learning/mysite/polls/views.py
# for 404s and obv rendering
from django.shortcuts import render, get_object_or_404

# for 404s, else idk
from django.http import HttpResponse, HttpResponseRedirect, Http404

# template importing 
from django.template import loader

# not sure what reverse does exactly - used in vote - some kind of POST function
from django.urls import reverse

# pulls defaults for views - this helps us set up templating
# i.e. - /detail.html pulls from /detail_detail.html like pug and mixins
from django.views import generic

# Create your views here.

# pulls data from models.py
from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # return the last five published questions
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    # template_name overrides defaults - as a DetailView with the 
    # model = question => default filename = question_detail.html
   # template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    # /* old code*/ return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except:
        # rediplay question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a 
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


""" /* old code - see urls.py */
def index(request):
    # /*original code*/ return HttpResponse("Hello world. You're at the polls index.")
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list' : latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})
    # /*old code*/ return HttpResponse("You're looking at the results of question %s." % question_id)

def results(request, question_id):
    # /*old code*/ response = "You're looking at the results of question %s."
    # /*old code*/ return HttpResponse(response % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

"""

django-learning/mysite/polls/templates/polls/detail.html
<h1>
    {{ question.question_text }}
</h1>

{% if error_message %}
<p><strong>
    {{ error_message }}
</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input  type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
        </label>
        <br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

<!-- /*old code*/ ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }}
    </li>
    {% endfor %}
</ul-->

django-learning/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <!-- /*old_hardcoded*/ a href="/polls/{{ question.id }}/">
        this works via the router in urls.py
        polls:detail added because urls.py now sees urlpatterns under 'polls' app_name namespace-->
        <a href="{% url 'polls:detail' question.id%}">
        {{ question.question_text }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls available.</p>
{% endif %}

django-learning/mysite/polls/templates/polls/question_detail.html
<h1>
    {{ question.question_text }}
</h1>

{% if error_message %}
<p><strong>
    {{ error_message }}
</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input  type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
        </label>
        <br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

<!-- /*old code*/ ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }}
    </li>
    {% endfor %}
</ul-->

django-learning/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>